/**
 * session-running tool — record initial "running" state for a detached session.
 *
 * Called by the session babysitter immediately after spawning claude.
 * Writes a SessionDoc with status: 'running' to the sessions book,
 * which fires CDC so the Laboratory observes session start.
 *
 * This replaces the in-process recordRunning() path for detached sessions.
 * The existing in-process path continues to work for non-detached sessions.
 *
 * See: docs/architecture/detached-sessions.md
 */

import { tool } from '@shardworks/tools-apparatus';
import { guild } from '@shardworks/nexus-core';
import { z } from 'zod';
import type { StacksApi } from '@shardworks/stacks-apparatus';
import type { SessionDoc } from '../types.ts';
import { emitSessionStarted } from '../session-emission.ts';
import { TERMINAL_STATUSES, reduceSessionTransition } from '../session-reducer.ts';

export default tool({
  name: 'session-running',
  description: 'Record initial running state for a detached session',
  instructions:
    'Called by session babysitters to record that a detached session has started. ' +
    'Writes a SessionDoc with status "running" to the sessions book. ' +
    'Not intended for patron or anima use.',
  params: {
    sessionId: z.string().describe('The session ID (pre-generated by the Animator at dispatch time)'),
    startedAt: z.string().describe('ISO timestamp of session start'),
    provider: z.string().describe('Provider name (e.g. "claude-code")'),
    conversationId: z.string().optional().describe('For --resume sessions'),
    metadata: z.record(z.string(), z.unknown()).optional().describe('Session metadata (writId, engineId, etc.)'),
    cancelHandle: z.union([
      z.object({ kind: z.literal('local-pgid'), pgid: z.number() }),
    ]).optional().describe('Tagged cancel handle for cross-process cancellation'),
  },
  callableBy: 'anima',
  permission: 'write',
  handler: async (params) => {
    const stacks = guild().apparatus<StacksApi>('stacks');
    const sessions = stacks.book<SessionDoc>('animator', 'sessions');

    // Merge with any pre-existing doc (e.g. the `pending` record written by
    // launchDetached before the babysitter was spawned).
    const existing = await sessions.get(params.sessionId);

    // Terminal-state guard: a late or duplicate ready report must not regress
    // a session that has already reached a terminal state. The reducer's
    // terminal-immutability rule would also produce this no-op, but the
    // call site needs the early return to keep its `status` in the
    // response body for callers that branch on it.
    if (existing && TERMINAL_STATUSES.has(existing.status)) {
      console.warn(
        `[animator] Ignoring session-running for ${params.sessionId} (already ${existing.status})`,
      );
      return { ok: true, sessionId: params.sessionId, status: existing.status };
    }

    // Both the pending→running normal path and the running→running
    // refresh path go through the reducer's `detached-ready` variant —
    // the reducer detects the running→running case internally (D9) and
    // applies the metadata-preserving refresh.
    const doc = reduceSessionTransition(existing, {
      kind: 'detached-ready',
      id: params.sessionId,
      startedAt: params.startedAt,
      provider: params.provider,
      lastActivityAt: new Date().toISOString(),
      ...(params.conversationId ? { conversationId: params.conversationId } : {}),
      ...(params.metadata ? { metadata: params.metadata } : {}),
      ...(params.cancelHandle ? { cancelHandle: params.cancelHandle } : {}),
    });

    await sessions.put(doc);

    // Detached running tool — fire `session.started` for the canonical
    // first-time pending → running transition. Compare pre-reducer
    // existing.status against the post-reducer status: the
    // running→running refresh path leaves status at `'running'` so the
    // `existing?.status !== 'running'` guard suppresses the duplicate
    // emission, exactly as before.
    if (existing?.status !== 'running' && doc.status === 'running') {
      await emitSessionStarted(doc);
    }

    return { ok: true, sessionId: params.sessionId };
  },
});
