/**
 * session-running tool — record initial "running" state for a detached session.
 *
 * Called by the session babysitter immediately after spawning claude.
 * Writes a SessionDoc with status: 'running' to the sessions book,
 * which fires CDC so the Laboratory observes session start.
 *
 * This replaces the in-process recordRunning() path for detached sessions.
 * The existing in-process path continues to work for non-detached sessions.
 *
 * See: docs/architecture/detached-sessions.md
 */

import { tool } from '@shardworks/tools-apparatus';
import { guild } from '@shardworks/nexus-core';
import { z } from 'zod';
import type { StacksApi } from '@shardworks/stacks-apparatus';
import type { SessionDoc } from '../types.ts';

export default tool({
  name: 'session-running',
  description: 'Record initial running state for a detached session',
  instructions:
    'Called by session babysitters to record that a detached session has started. ' +
    'Writes a SessionDoc with status "running" to the sessions book. ' +
    'Not intended for patron or anima use.',
  params: {
    sessionId: z.string().describe('The session ID (pre-generated by the Animator at dispatch time)'),
    startedAt: z.string().describe('ISO timestamp of session start'),
    provider: z.string().describe('Provider name (e.g. "claude-code")'),
    conversationId: z.string().optional().describe('For --resume sessions'),
    metadata: z.record(z.string(), z.unknown()).optional().describe('Session metadata (writId, engineId, etc.)'),
    cancelMetadata: z.record(z.string(), z.unknown()).optional().describe('Includes { pid } for cross-process cancellation'),
  },
  callableBy: 'anima',
  permission: 'write',
  handler: async (params) => {
    const stacks = guild().apparatus<StacksApi>('stacks');
    const sessions = stacks.book<SessionDoc>('animator', 'sessions');

    // Merge with any pre-existing doc (e.g. the `pending` record written by
    // launchDetached before the babysitter was spawned). Preserve
    // authorizedTools, existing metadata, and any other fields the caller
    // may not have passed.
    const existing = await sessions.get(params.sessionId);

    const doc: SessionDoc = {
      ...(existing ?? {}),
      id: params.sessionId,
      status: 'running',
      startedAt: existing?.startedAt ?? params.startedAt,
      provider: existing?.provider ?? params.provider,
      ...(params.conversationId ? { conversationId: params.conversationId } : {}),
      ...(params.metadata ? { metadata: { ...(existing?.metadata ?? {}), ...params.metadata } } : {}),
      ...(params.cancelMetadata
        ? { cancelMetadata: { ...(existing?.cancelMetadata ?? {}), ...params.cancelMetadata } }
        : {}),
    };

    await sessions.put(doc);

    return { ok: true, sessionId: params.sessionId };
  },
});
