/**
 * The Animator — public types.
 *
 * These types form the contract between The Animator apparatus and all
 * callers (summon relay, nsg consult, etc.). No implementation details.
 *
 * See: docs/specification.md (animator)
 */

import type { AnimaWeave } from '@shardworks/loom-apparatus';
import type { ResolvedTool } from '@shardworks/tools-apparatus';

// ── Session chunks (streaming output) ────────────────────────────────

/** A chunk of output from a running session. */
export type SessionChunk =
  | { type: 'text'; text: string }
  | { type: 'tool_use'; tool: string }
  | { type: 'tool_result'; tool: string };

// ── Request / Result ─────────────────────────────────────────────────

export interface AnimateRequest {
  /**
   * Optional pre-generated session id. When provided, the Animator uses
   * this id instead of generating a new one. Used by summon() to make the
   * session id available on the handle before the Loom weave resolves.
   */
  sessionId?: string;
  /** The anima weave from The Loom (composed identity context). */
  context: AnimaWeave;
  /**
   * The work prompt — what the anima should do.
   * Passed directly to the session provider as the initial prompt.
   * This bypasses The Loom — it is not a composition concern.
   */
  prompt?: string;
  /**
   * Working directory for the session.
   * The session provider launches the AI process here.
   */
  cwd: string;
  /**
   * Optional conversation id to resume a multi-turn conversation.
   * If provided, the session provider resumes the existing conversation
   * rather than starting a new one.
   */
  conversationId?: string;
  /**
   * Caller-supplied metadata recorded alongside the session.
   * The Animator stores this as-is — it does not interpret the contents.
   */
  metadata?: Record<string, unknown>;
  /**
   * Enable streaming output. When true, the returned `chunks` iterable
   * yields output as the session produces it. When false (default), the
   * `chunks` iterable completes immediately with no items.
   *
   * Either way, the return shape is the same: `{ chunks, result }`.
   */
  streaming?: boolean;
  /**
   * Task-layer environment variables. Overrides the identity-layer
   * environment from the AnimaWeave when keys collide. Spread into the
   * spawned process environment.
   */
  environment?: Record<string, string>;
}

export interface SessionResult {
  /** Unique session id (generated by The Animator). */
  id: string;
  /**
   * Terminal status.
   *
   * `'rate-limited'` signals that the session terminated because the
   * underlying anima provider reported (or was detected to be) rate
   * limited. Callers that dispatched through The Animator see this as
   * a first-class terminal outcome distinct from `'failed'`, so that
   * the Animator's back-off gate can govern the next dispatch and
   * engines/rigs can route to the reversible-wait path rather than
   * treating the session as a generic failure.
   */
  status: 'completed' | 'failed' | 'timeout' | 'cancelled' | 'rate-limited';
  /** When the session started (ISO-8601). */
  startedAt: string;
  /** When the session ended (ISO-8601). */
  endedAt: string;
  /** Wall-clock duration in milliseconds. */
  durationMs: number;
  /** Provider name (e.g. 'claude-code'). */
  provider: string;
  /** Numeric exit code from the provider process. */
  exitCode: number;
  /** Error message if failed. */
  error?: string;
  /** Conversation id (for multi-turn resume). */
  conversationId?: string;
  /** Session id from the provider (e.g. for --resume). */
  providerSessionId?: string;
  /** Token usage from the provider, if available. */
  tokenUsage?: TokenUsage;
  /** Cost in USD from the provider, if available. */
  costUsd?: number;
  /** Caller-supplied metadata, recorded as-is. */
  metadata?: Record<string, unknown>;
  /**
   * The final assistant text from the session.
   * Extracted by the Animator from the provider's transcript.
   * Useful for programmatic consumers that need the session's conclusion
   * without parsing the full transcript (e.g. the Spider's review collect step).
   */
  output?: string;
  /**
   * Structured termination tag attached by the session provider when the
   * terminal status reflects a specific detected condition (today:
   * rate-limit detection). Absent when the terminal status has no extra
   * structure. Consumers that just need the outcome should branch on
   * `status`; the Animator's back-off machine uses this tag to
   * disambiguate rate-limit terminations from generic failures.
   */
  terminationTag?: SessionTerminationTag;
}

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
}

// ── Bulk session cost lookup ─────────────────────────────────────────

/**
 * Per-session cost snapshot returned by AnimatorApi.getSessionCosts().
 *
 * A projection of the cost/token fields on SessionDoc — sufficient for
 * bulk cost aggregation (rig-level totals, per-engine breakdowns) without
 * forcing the caller to reach into the sessions book directly. Consumers
 * that need other session fields should look them up via SessionDoc.
 */
export interface SessionCost {
  /**
   * Cost in USD as reported by the session. Zero when the session exists
   * but has not reported a cost (e.g. still running, or the provider did
   * not record one).
   */
  costUsd: number;
  /** Input tokens from the session's tokenUsage, if the provider reported it. */
  inputTokens?: number;
  /** Output tokens from the session's tokenUsage, if the provider reported it. */
  outputTokens?: number;
}

// ── Summon request ──────────────────────────────────────────────────

export interface SummonRequest {
  /**
   * The work prompt — what the anima should do.
   * Passed directly to the session provider as the initial prompt.
   */
  prompt: string;
  /**
   * The role to summon (e.g. 'artificer', 'scribe').
   * Passed to The Loom for context composition and recorded in session metadata.
   */
  role?: string;
  /**
   * Working directory for the session.
   * The session provider launches the AI process here.
   */
  cwd: string;
  /**
   * Optional conversation id to resume a multi-turn conversation.
   */
  conversationId?: string;
  /**
   * Additional metadata to record alongside the session.
   * Merged with auto-generated metadata (trigger: 'summon', role).
   */
  metadata?: Record<string, unknown>;
  /**
   * Enable streaming output. When true, the returned `chunks` iterable
   * yields output as the session produces it. When false (default), the
   * `chunks` iterable completes immediately with no items.
   */
  streaming?: boolean;
  /**
   * Task-layer environment variables. Overrides the identity-layer
   * environment from the AnimaWeave when keys collide. Spread into the
   * spawned process environment.
   */
  environment?: Record<string, string>;
}

// ── Animator API (the `provides` interface) ──────────────────────────

/** The return value from animate() and summon(). */
export interface AnimateHandle {
  /**
   * Session ID, available immediately after launch — before the session
   * completes. Callers that only need to know the session was launched
   * (e.g. quick engines returning `{ status: 'launched', sessionId }`)
   * can return without awaiting `result`.
   */
  sessionId: string;
  /**
   * Async iterable of output chunks from the session. When streaming is
   * disabled (the default), this iterable completes immediately with no
   * items. When streaming is enabled, it yields chunks as the session
   * produces output.
   */
  chunks: AsyncIterable<SessionChunk>;
  /**
   * Promise that resolves to the final SessionResult after the session
   * completes (or fails/times out) and the result is recorded to The Stacks.
   */
  result: Promise<SessionResult>;
}

export interface AnimatorApi {
  /**
   * Summon an anima — compose context via The Loom and launch a session.
   *
   * This is the high-level "make an anima do a thing" entry point.
   * Internally calls The Loom for context composition (passing the role),
   * then animate() for session launch and recording. The work prompt
   * bypasses the Loom and goes directly to the provider.
   *
   * Requires The Loom apparatus to be installed. Throws if not available.
   *
   * Auto-populates session metadata with `trigger: 'summon'` and `role`.
   *
   * Returns synchronously — the async work lives inside `result` and `chunks`.
   */
  summon(request: SummonRequest): AnimateHandle;

  /**
   * Animate a session — launch an AI process with the given context.
   *
   * This is the low-level entry point for callers that compose their own
   * AnimaWeave (e.g. The Parlour for multi-turn conversations).
   *
   * Records the session result to The Stacks before `result` resolves.
   *
   * Set `streaming: true` on the request to receive output chunks as the
   * session runs. When streaming is disabled (default), the `chunks`
   * iterable completes immediately with no items.
   *
   * Returns synchronously — the async work lives inside `result` and `chunks`.
   */
  animate(request: AnimateRequest): AnimateHandle;

  /**
   * Subscribe to a running session's output stream.
   *
   * Returns an AsyncIterable that replays all chunks already produced
   * (from session start) and then yields new chunks as they arrive.
   * Returns null if there is no active in-memory session with the given id
   * (i.e. the session is unknown, already completed, or started before this
   * process started).
   *
   * When the session ends, the iterable completes automatically.
   */
  subscribeToSession(sessionId: string): AsyncIterable<SessionChunk> | null;

  /**
   * Cancel a running session.
   *
   * Patches the SessionDoc to 'cancelled' with endedAt, durationMs, and
   * the optional reason in the error field. If cancelHandle is available,
   * delegates to the provider's cancel() method to kill the process.
   *
   * Idempotent: if the session is already in a terminal state, returns the
   * existing SessionDoc without modification. Throws if the session ID
   * does not exist.
   *
   * Does NOT wait for the process to die — returns immediately after
   * patching and sending the kill signal.
   */
  cancel(sessionId: string, options?: { reason?: string }): Promise<SessionDoc>;

  /**
   * Bulk per-session cost/token lookup — the first read-side helper on
   * AnimatorApi. Resolves cost and token-usage snapshots for the given
   * session ids in a single round-trip against the sessions book.
   *
   * Returns a Map keyed by session id. Session ids not present in the
   * sessions book are omitted from the returned Map — callers decide
   * whether that means "zero contribution" (as Spider's rig-view does) or
   * something else.
   *
   * Empty input returns an empty Map without touching The Stacks.
   *
   * Intended for UI-facing aggregators that compose rig-level totals or
   * per-engine breakdowns. The shape is deliberately minimal: callers that
   * need other SessionDoc fields should look them up separately.
   */
  getSessionCosts(sessionIds: string[]): Promise<Map<string, SessionCost>>;

  /**
   * Return the current Animator status document verbatim.
   *
   * Exposes the back-off state machine's persisted state — pause phase,
   * window bounds, back-off level, and triggering session — to callers
   * (Spider's crawl gate, the `animator-status` CLI tool, the
   * `GET /api/animator/status` HTTP route, the Oculus banner). Consumers
   * compose their own dispatchability predicate; the Animator does not
   * decide for them.
   *
   * Returns an AnimatorStatusDoc with `state: 'running'` and
   * `backoffLevel: 0` on fresh installs that have never hit a rate
   * limit — the shape is always defined so callers don't need a null
   * check.
   */
  getStatus(): Promise<AnimatorStatusDoc>;
}

// ── Session provider interface ───────────────────────────────────────

/**
 * A session provider — pluggable backend that knows how to launch and
 * communicate with a specific AI system.
 *
 * Implemented as an apparatus plugin whose `provides` object satisfies
 * this interface. The Animator discovers the provider via guild config:
 * `guild.json["animator"]["sessionProvider"]` names the plugin id.
 *
 * The provider always returns `{ chunks, result }` — the same shape as
 * AnimateHandle. When `config.streaming` is true, the provider MAY yield
 * output chunks as the session runs. When false (or when the provider
 * does not support streaming), the chunks iterable completes immediately
 * with no items. The Animator does not branch on streaming capability —
 * it passes the flag through and trusts the provider to do the right thing.
 */
export interface AnimatorSessionProvider {
  /** Human-readable name (e.g. 'claude-code'). */
  name: string;

  /**
   * Launch a session. Returns `{ chunks, result }` synchronously.
   *
   * The `result` promise resolves when the AI process exits.
   * The `chunks` async iterable yields output when `config.streaming`
   * is true and the provider supports streaming; otherwise it completes
   * immediately with no items.
   *
   * Providers that don't support streaming simply ignore the flag and
   * return empty chunks — no separate method needed.
   */
  launch(config: SessionProviderConfig): {
    chunks: AsyncIterable<SessionChunk>;
    result: Promise<SessionProviderResult>;
    /**
     * Provider-specific process metadata for cross-process cancellation.
     * Resolves as soon as the process is spawned. The Animator persists the
     * resolved value as `cancelHandle` on the SessionDoc.
     *
     * Optional — providers that don't support cancellation omit this.
     */
    processInfo?: Promise<Record<string, unknown>>;
  };

  /**
   * Cancel a running session using previously persisted process metadata.
   *
   * Called by the Animator with the cancelMetadata from the SessionDoc.
   * The provider interprets the metadata and kills the process.
   *
   * Optional — providers that don't support cancellation omit this.
   */
  cancel?(cancelMetadata: Record<string, unknown>): Promise<void>;
}

export interface SessionProviderConfig {
  /**
   * Pre-generated session id. The Animator generates this before calling
   * launch() so both sides share the same id. Providers that spawn detached
   * processes need this to correlate lifecycle events (session-running,
   * session-record) back to the Animator's session record.
   */
  sessionId: string;
  /** System prompt for the AI process. May be undefined if composition is not yet implemented. */
  systemPrompt?: string;
  /** Initial user message (e.g. writ description). */
  initialPrompt?: string;
  /** Model to use (from guild settings). */
  model: string;
  /** Optional conversation id for resume. */
  conversationId?: string;
  /** Working directory for the session. */
  cwd: string;
  /**
   * Enable streaming output. When true, the provider should yield output
   * chunks as the session produces them. When false (default), the chunks
   * iterable should complete immediately with no items.
   *
   * Providers that don't support streaming may ignore this flag.
   */
  streaming?: boolean;
  /**
   * Resolved tools for this session. When present, the provider should
   * configure an MCP server with these tool definitions.
   *
   * The Loom resolves role → permissions → tools via the Instrumentarium.
   * The Animator passes them through from the AnimaWeave.
   */
  tools?: ResolvedTool[];
  /**
   * Merged environment variables to spread into the spawned process.
   * The Animator merges identity-layer (weave) and task-layer (request)
   * variables before passing them here — task layer wins on collision.
   */
  environment?: Record<string, string>;
}

/** A single message from the NDJSON stream. Untyped — shape varies by provider. */
export type TranscriptMessage = Record<string, unknown>;

/**
 * Structured termination tag attached by a session provider when it
 * detects a specific non-generic reason for a session's terminal state.
 *
 * Today the only kind is `'rate-limit'` — the claude-code provider raises
 * this when it observes a rate-limit signature on the NDJSON result,
 * stderr stream, or exit code. The Animator consumes the tag to drive
 * its back-off state machine; consumers that only care about the outcome
 * can ignore the tag and branch on status instead.
 *
 * The shape is deliberately open: the `source` field records which signal
 * fired so the cascade order is auditable from the SessionDoc, and new
 * kinds can be added (e.g. future operator-triggered termination)
 * without breaking existing consumers.
 */
export interface SessionTerminationTag {
  /** Reason discriminator. */
  kind: 'rate-limit';
  /** Which provider signal fired the detection. */
  source: 'ndjson-result' | 'stderr-pattern' | 'exit-code';
  /** Optional operator-facing explanation from the provider. */
  detail?: string;
}

export interface SessionProviderResult {
  /** Exit status. */
  status: 'completed' | 'failed' | 'timeout' | 'cancelled' | 'rate-limited';
  /**
   * Structured termination tag. Providers set this when the terminal
   * status was produced by a specific detected condition (today: rate
   * limiting). Absent when the terminal status has no extra structure.
   */
  terminationTag?: SessionTerminationTag;
  /** Numeric exit code from the process. */
  exitCode: number;
  /** Error message if failed. */
  error?: string;
  /** Provider's session id (e.g. for --resume). */
  providerSessionId?: string;
  /** Token usage, if the provider can report it. */
  tokenUsage?: TokenUsage;
  /** Cost in USD, if the provider can report it. */
  costUsd?: number;
  /**
   * The session's full transcript — array of NDJSON message objects.
   *
   * In attached mode, this is populated directly from the NDJSON stream.
   * In detached mode, the transcript is written to SQLite by the babysitter
   * and is available via `stacks.book('animator', 'transcripts').get(sessionId)`
   * rather than on this result object.
   */
  transcript?: TranscriptMessage[];
  /**
   * The final assistant text from the session.
   * Extracted from the last assistant message's text content blocks.
   * Undefined if the session produced no assistant output.
   */
  output?: string;
  /** Process signal name if the session was killed by signal (e.g. 'SIGTERM', 'SIGKILL'). */
  signal?: string;
}

// ── Stacks document type ─────────────────────────────────────────────

/**
 * The session document stored in The Stacks' `sessions` book.
 * Includes all SessionResult fields plus the `id` required by BookEntry.
 */
export interface SessionDoc {
  id: string;
  /**
   * Session status. Initially written as `'running'` when the session is
   * launched, then updated to a terminal status (`'completed'`, `'failed'`,
   * `'timeout'`, or `'cancelled'`) after the provider exits or cancel is called.
   * The `'running'` state is transient.
   * `SessionResult.status` only includes terminal states.
   */
  status: 'pending' | 'running' | 'completed' | 'failed' | 'timeout' | 'cancelled' | 'rate-limited';
  startedAt: string;
  endedAt?: string;
  durationMs?: number;
  provider: string;
  exitCode?: number;
  error?: string;
  conversationId?: string;
  providerSessionId?: string;
  tokenUsage?: TokenUsage;
  costUsd?: number;
  metadata?: Record<string, unknown>;
  /** The final assistant text from the session. */
  output?: string;
  /**
   * Provider-owned opaque handle for cross-process cancellation.
   * Written by the Animator from the provider's processInfo at session launch.
   * The Animator does not interpret this — it passes it back to the provider's
   * cancel() method when cancellation is requested.
   *
   * Shape is tagged by host type:
   * - local process: { kind: 'local-pgid', pgid: number }
   * - future container: { kind: 'container', containerId: string }
   * - future remote: { kind: 'remote', jobId: string, host: string }
   */
  cancelHandle?: Record<string, unknown>;
  /**
   * ISO timestamp of the last lifecycle signal from the session host.
   *
   * Updated on: pending pre-write, ready report (session-running),
   * heartbeat, terminal report (session-record). The guild writes its
   * own wall-clock time — never a host-supplied timestamp.
   *
   * The reconciler uses this to detect dead sessions:
   *   if (now - lastActivityAt - downtimeCredit > stalenessThreshold) → failed
   *
   * See: docs/architecture/detached-sessions.md § Reconciliation
   */
  lastActivityAt?: string;
  /**
   * Tool names this session is authorized to call over the Tool HTTP API.
   *
   * Source of truth for the daemon's Stacks-backed authorize callback.
   * Pre-written by `launchDetached()` (or animate()) before the babysitter
   * is spawned, then preserved through subsequent updates.
   */
  authorizedTools?: string[];
  /**
   * Structured termination tag, mirroring SessionResult.terminationTag.
   * Persisted on the SessionDoc so callers that read sessions out of The
   * Stacks (Spider's tryCollect, UI inspectors, the Laboratory CDC
   * stream) can tell why the session terminated without re-running the
   * provider's cascade. Set when the provider emits one via
   * `session-record`, preserved across status patches.
   */
  terminationTag?: SessionTerminationTag;
  /** Index signature required by BookEntry. */
  [key: string]: unknown;
}

/**
 * The transcript document stored in The Stacks' `transcripts` book.
 * One record per session — 1:1 relationship with SessionDoc.
 */
export interface TranscriptDoc {
  /** Same as the session id. */
  id: string;
  /** Full NDJSON transcript from the session. */
  messages: TranscriptMessage[];
  /** Index signature required by BookEntry. */
  [key: string]: unknown;
}

/**
 * Operational state stored in the Animator's 'state' book.
 * Single well-known document with id 'guild-heartbeat'.
 */
export interface GuildStateDoc {
  id: string;
  /** ISO timestamp of the last guild self-heartbeat. */
  guildAliveAt: string;
  /** Index signature required by BookEntry. */
  [key: string]: unknown;
}

// ── Animator status doc (rate-limit back-off) ────────────────────────

/**
 * Reason for the Animator's current pause state. Extensible — today only
 * `'rate-limit'` is produced, but the field is open so future operator-
 * triggered pause can reuse the same doc shape without a schema bump.
 */
export type AnimatorPauseReason = 'rate-limit';

/**
 * Operational state stored in the Animator's 'status' book.
 *
 * Single well-known document with id 'current'. Tracks whether the
 * anima provider is currently rate-limited, when the current pause
 * window ends, and the exponential back-off level that will be applied
 * to the next pause.
 *
 * Consumers (Spider's crawl gate, the Oculus banner, the
 * `animator-status` CLI tool) dispatch sessions only when:
 *   state === 'running' OR pausedUntil <= now
 * The combined check tolerates the "stale running" edge cases — a daemon
 * restart leaves the doc in its last persisted state; the first
 * successful dispatch naturally flips it back to `'running'` (D24).
 */
export interface AnimatorStatusDoc {
  id: string;
  /** Current pause state. `'running'` means sessions dispatch normally. */
  state: 'running' | 'paused';
  /** ISO timestamp when the current pause began. Absent when running. */
  pausedSince?: string;
  /**
   * ISO timestamp when the current pause window is due to clear.
   * Consumers must combine this with `state` to decide dispatchability.
   * Absent when running.
   */
  pausedUntil?: string;
  /** Reason for the current pause. Absent when running. */
  pauseReason?: AnimatorPauseReason;
  /**
   * Current back-off level. Starts at 0 for the first pause; only
   * increments when a rate-limit hit arrives *after* a resume attempt
   * has dispatched. Reset to 0 on any non-rate-limit terminal. (D7, D8)
   */
  backoffLevel: number;
  /** ISO timestamp of the most recent rate-limit hit, across all pauses. */
  backoffLastHitAt?: string;
  /** Session id that produced the current (or most recent) pause. */
  lastTriggeringSession?: string;
  /** Index signature required by BookEntry. */
  [key: string]: unknown;
}

// ── Animator config ──────────────────────────────────────────────────

/**
 * Rate-limit back-off configuration — lives under
 * `guild.json["animator"]["rateLimitBackoff"]`.
 *
 * Validated fail-loud at animator startup (D10 — patron override of the
 * silent-default convention applied *only* to this block). The block is
 * optional; missing values fall back to the defaults documented below.
 */
export interface AnimatorRateLimitBackoffConfig {
  /**
   * Initial pause duration in milliseconds (back-off level 0). Must be a
   * positive integer. Default: 15 minutes (900_000).
   */
  initialMs?: number;
  /**
   * Upper bound for the pause window after exponential back-off. Must be
   * a positive integer greater than or equal to `initialMs`. Default:
   * 1 hour (3_600_000).
   */
  maxMs?: number;
  /**
   * Multiplier applied per successive failed resume attempt. Must be a
   * finite number greater than 1. Default: 2.
   */
  factor?: number;
}

/** Plugin configuration stored at guild.json["animator"]. */
export interface AnimatorConfig {
  /**
   * Plugin id of the apparatus that implements AnimatorSessionProvider.
   * The Animator looks this up via guild().apparatus() at animate-time.
   * Defaults to 'claude-code' if not specified.
   */
  sessionProvider?: string;
  /**
   * Rate-limit back-off tuning. Optional; each field falls back to its
   * documented default when absent. Malformed values throw at startup.
   */
  rateLimitBackoff?: AnimatorRateLimitBackoffConfig;
}

// Augment GuildConfig so `guild().guildConfig().animator` is typed without
// requiring a manual type parameter at the call site.
declare module '@shardworks/nexus-core' {
  interface GuildConfig {
    animator?: AnimatorConfig;
  }
}
