/**
 * Spider UI — static asset regression tests.
 *
 * These tests verify the HTML structure generated by spider.js for the rig
 * list table.  Because spider.js is a vanilla-JS IIFE (no modules), we
 * validate the source text directly to ensure structural invariants hold.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const spiderJs = readFileSync(resolve(__dirname, 'spider.js'), 'utf-8');

// ── Rig list row structure ──────────────────────────────────────────────

describe('spider.js rig list row HTML', () => {
  it('renders the writ-title cell as a rig-link anchor', () => {
    // The row template should contain a <td> with a rig-link anchor for the
    // writ title (the second <td> in each row).  We match the template
    // fragment that builds the writ-title cell.
    const writTitleCellPattern =
      /<td><a class="rig-link" href="#" data-rig-id="[^"]*"\s*>\s*'\s*\+\s*esc\(writTitle\)/;
    assert.match(
      spiderJs,
      writTitleCellPattern,
      'writ-title cell should be a clickable rig-link anchor',
    );
  });

  it('renders the rig-id cell as a rig-link anchor', () => {
    const rigIdCellPattern =
      /<td><a class="rig-link" href="#" data-rig-id="[^"]*"\s*>\s*'\s*\+\s*esc\(rig\.id\)/;
    assert.match(
      spiderJs,
      rigIdCellPattern,
      'rig-id cell should be a clickable rig-link anchor',
    );
  });

  it('writ-title and rig-id cells share the same rig-link class', () => {
    // Both cells must use the same class so the click handler wires them
    // identically.  Count rig-link anchors in the row template.
    const rowTemplateMatch = spiderJs.match(
      /var rows = filtered\.map\(function \(rig\) \{[\s\S]*?\.join\(''\)/,
    );
    assert.ok(rowTemplateMatch, 'should find the row template block');
    const rowTemplate = rowTemplateMatch[0];

    const rigLinkCount = (rowTemplate.match(/class="rig-link"/g) || []).length;
    assert.ok(
      rigLinkCount >= 2,
      `expected at least 2 rig-link anchors in the row template, found ${rigLinkCount}`,
    );
  });

  it('writ-title cell is NOT rendered as plain text', () => {
    // Regression guard: the old pattern was just  '<td>' + esc(writTitle) + '</td>'
    // with no anchor.  Ensure that pattern no longer exists.
    const plainTitlePattern = /'<td>'\s*\+\s*esc\(writTitle\)\s*\+\s*'<\/td>'/;
    assert.doesNotMatch(
      spiderJs,
      plainTitlePattern,
      'writ-title cell must not be rendered as plain (non-linked) text',
    );
  });
});
