/**
 * Spider UI — static asset regression tests.
 *
 * These tests verify the HTML structure generated by spider.js for the rig
 * list table.  Because spider.js is a vanilla-JS IIFE (no modules), we
 * validate the source text directly to ensure structural invariants hold.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const spiderJs = readFileSync(resolve(__dirname, 'spider.js'), 'utf-8');
const spiderCss = readFileSync(resolve(__dirname, 'spider.css'), 'utf-8');
const indexHtml = readFileSync(resolve(__dirname, 'index.html'), 'utf-8');

// ── Rig list row structure ──────────────────────────────────────────────

describe('spider.js rig list row HTML', () => {
  it('renders the writ-title cell as a rig-link anchor', () => {
    // The row template should contain a <td> with a rig-link anchor for the
    // writ title (the second <td> in each row).  We match the template
    // fragment that builds the writ-title cell.
    const writTitleCellPattern =
      /<td><a class="rig-link" href="#" data-rig-id="[^"]*"\s*>\s*'\s*\+\s*esc\(writTitle\)/;
    assert.match(
      spiderJs,
      writTitleCellPattern,
      'writ-title cell should be a clickable rig-link anchor',
    );
  });

  it('renders the rig-id cell as a rig-link anchor', () => {
    const rigIdCellPattern =
      /<td><a class="rig-link" href="#" data-rig-id="[^"]*"\s*>\s*'\s*\+\s*esc\(rig\.id\)/;
    assert.match(
      spiderJs,
      rigIdCellPattern,
      'rig-id cell should be a clickable rig-link anchor',
    );
  });

  it('writ-title and rig-id cells share the same rig-link class', () => {
    // Both cells must use the same class so the click handler wires them
    // identically.  Count rig-link anchors in the row template.
    const rowTemplateMatch = spiderJs.match(
      /var rows = filtered\.map\(function \(rig\) \{[\s\S]*?\.join\(''\)/,
    );
    assert.ok(rowTemplateMatch, 'should find the row template block');
    const rowTemplate = rowTemplateMatch[0];

    const rigLinkCount = (rowTemplate.match(/class="rig-link"/g) || []).length;
    assert.ok(
      rigLinkCount >= 2,
      `expected at least 2 rig-link anchors in the row template, found ${rigLinkCount}`,
    );
  });

  it('writ-title cell is NOT rendered as plain text', () => {
    // Regression guard: the old pattern was just  '<td>' + esc(writTitle) + '</td>'
    // with no anchor.  Ensure that pattern no longer exists.
    const plainTitlePattern = /'<td>'\s*\+\s*esc\(writTitle\)\s*\+\s*'<\/td>'/;
    assert.doesNotMatch(
      spiderJs,
      plainTitlePattern,
      'writ-title cell must not be rendered as plain (non-linked) text',
    );
  });

  it('writ deep-links target the canonical Clerk writs page path', () => {
    // Regression guard: historically, writ-id anchors in the rig view and
    // rig-list row targeted '/pages/clerk/?writ=…', but no plugin registers
    // a page with id 'clerk' — the Clerk's writs page is registered with id
    // 'writs' and served at '/pages/writs/'. That produced a bare 404 on
    // every click. Pin the canonical URL shape, matching the Ratchet
    // linkDispatch helper, and forbid the broken one.
    assert.match(
      spiderJs,
      /\/pages\/writs\/\?writ=/,
      'writ deep-links must target /pages/writs/?writ=',
    );
    assert.doesNotMatch(
      spiderJs,
      /\/pages\/clerk\/\?writ=/,
      'writ deep-links must NOT target the broken /pages/clerk/?writ= path',
    );
  });
});

// ── Cancellation UI ──────────────────────────────────────────────────────

describe('spider.js cancel button', () => {
  it('renders a cancel button with id "cancel-engine-btn"', () => {
    assert.match(
      spiderJs,
      /id="cancel-engine-btn"/,
      'should contain a cancel button element',
    );
  });

  it('cancel button has btn--danger class', () => {
    assert.match(
      spiderJs,
      /class="btn btn--danger" id="cancel-engine-btn"/,
      'cancel button should have btn--danger class',
    );
  });

  it('cancel button sends POST to /api/rig/cancel', () => {
    assert.match(
      spiderJs,
      /method:\s*'POST'/,
      'should use POST method for cancel request',
    );
    assert.match(
      spiderJs,
      /\/api\/rig\/cancel/,
      'should call the cancel API endpoint',
    );
  });

  it('cancel button is conditional on rig status running or blocked', () => {
    assert.match(
      spiderJs,
      /currentRig\.status === 'running' \|\| currentRig\.status === 'blocked'/,
      'showCancel should check for running or blocked rig status',
    );
  });

  it('cancel button is hidden for terminal rig statuses', () => {
    assert.match(
      spiderJs,
      /currentRig\.status === 'cancelled'/,
      'should check for cancelled status to hide button',
    );
  });

  it('cancel button does NOT use DELETE method', () => {
    // DELETE with JSON body is unreliable across HTTP stacks.
    // The cancel fetch must use POST to match the auto-generated tool route.
    const cancelFetchBlock = spiderJs.match(
      /fetch\('\/api\/rig\/cancel'[\s\S]*?\)/,
    );
    assert.ok(cancelFetchBlock, 'should find the cancel fetch call');
    assert.doesNotMatch(
      cancelFetchBlock[0],
      /method:\s*'DELETE'/,
      'cancel fetch must not use DELETE method',
    );
  });

  it('cancel handler uses the cancel API response directly (no redundant rig-show fetch)', () => {
    // After the cancel fetch, the handler should call r.json() on the cancel
    // response itself, not make a second fetch to /api/rig/show.
    const cancelBlock = spiderJs.match(
      /fetch\('\/api\/rig\/cancel'[\s\S]*?\.catch/,
    );
    assert.ok(cancelBlock, 'should find the cancel fetch chain');
    assert.doesNotMatch(
      cancelBlock[0],
      /fetch\('\/api\/rig\/show/,
      'cancel handler should not make a redundant rig-show fetch',
    );
  });

  it('cancel handler calls preventDefault on click event', () => {
    // The cancel click handler should call e.preventDefault() to guard
    // against any default button behaviour.
    const cancelHandler = spiderJs.match(
      /addEventListener\('click', function \(e\)[\s\S]*?e\.preventDefault\(\)/,
    );
    assert.ok(
      cancelHandler,
      'cancel click handler should accept the event and call preventDefault',
    );
  });
});

describe('spider.js badgeClass for cancelled', () => {
  it('badgeClass returns "badge--cancelled" for cancelled status', () => {
    assert.match(
      spiderJs,
      /case 'cancelled':\s*return 'badge--cancelled'/,
      'badgeClass should return badge--cancelled for cancelled status',
    );
  });

  it('cancelled is not grouped with pending in badgeClass', () => {
    // Ensure cancelled has its own case, not falling through with pending
    assert.doesNotMatch(
      spiderJs,
      /case 'pending':\s*case 'cancelled'/,
      'cancelled should not fall through with pending',
    );
  });
});

describe('spider.css cancelled badge styling', () => {
  it('contains .badge--cancelled rule', () => {
    assert.match(
      spiderCss,
      /\.badge--cancelled/,
      'spider.css should contain .badge--cancelled rule',
    );
  });

  it('.badge--cancelled has text-decoration: line-through', () => {
    assert.match(
      spiderCss,
      /\.badge--cancelled[\s\S]*?text-decoration:\s*line-through/,
      'badge--cancelled should have line-through text decoration',
    );
  });

  it('.badge--cancelled has opacity', () => {
    assert.match(
      spiderCss,
      /\.badge--cancelled[\s\S]*?opacity:\s*0\.6/,
      'badge--cancelled should have reduced opacity',
    );
  });
});

describe('index.html status filter includes cancelled', () => {
  it('status filter has cancelled option', () => {
    assert.match(
      indexHtml,
      /<option value="cancelled">cancelled<\/option>/,
      'status filter should include cancelled option',
    );
  });

  it('cancelled option appears after blocked', () => {
    const blockedIdx = indexHtml.indexOf('<option value="blocked">');
    const cancelledIdx = indexHtml.indexOf('<option value="cancelled">');
    assert.ok(cancelledIdx > blockedIdx, 'cancelled option should appear after blocked');
  });
});

// ── Rig auto-polling ────────────────────────────────────────────────────

describe('spider.js rig list polling', () => {
  it('declares rigListPollTimer state variable', () => {
    assert.match(
      spiderJs,
      /var rigListPollTimer\s*=\s*null/,
      'should declare rigListPollTimer state variable',
    );
  });

  it('declares currentRigPollTimer state variable', () => {
    assert.match(
      spiderJs,
      /var currentRigPollTimer\s*=\s*null/,
      'should declare currentRigPollTimer state variable',
    );
  });

  it('declares RIG_POLL_INTERVAL constant', () => {
    assert.match(
      spiderJs,
      /var RIG_POLL_INTERVAL\s*=\s*2000/,
      'should declare RIG_POLL_INTERVAL at 2000ms',
    );
  });

  it('defines isRigInFlight helper checking running and blocked', () => {
    assert.match(
      spiderJs,
      /function isRigInFlight\(rig\)/,
      'should define isRigInFlight helper',
    );
    assert.match(
      spiderJs,
      /rig\.status === 'running' \|\| rig\.status === 'blocked'/,
      'isRigInFlight should check running or blocked',
    );
  });

  it('defines stopRigListPoll that clears the interval', () => {
    assert.match(
      spiderJs,
      /function stopRigListPoll\(\)/,
      'should define stopRigListPoll',
    );
    assert.match(
      spiderJs,
      /clearInterval\(rigListPollTimer\)/,
      'stopRigListPoll should clear rigListPollTimer',
    );
  });

  it('defines stopCurrentRigPoll that clears the interval', () => {
    assert.match(
      spiderJs,
      /function stopCurrentRigPoll\(\)/,
      'should define stopCurrentRigPoll',
    );
    assert.match(
      spiderJs,
      /clearInterval\(currentRigPollTimer\)/,
      'stopCurrentRigPoll should clear currentRigPollTimer',
    );
  });

  it('starts rig list polling after fetchRigs succeeds', () => {
    // The fetchRigs promise chain should call startRigListPollIfNeeded
    const fetchRigsBlock = spiderJs.match(
      /function fetchRigs\([\s\S]*?\.catch/,
    );
    assert.ok(fetchRigsBlock, 'should find fetchRigs function');
    assert.match(
      fetchRigsBlock[0],
      /startRigListPollIfNeeded\(\)/,
      'fetchRigs should call startRigListPollIfNeeded after rendering',
    );
  });

  it('starts current rig polling in showRigDetail', () => {
    const showRigBlock = spiderJs.match(
      /function showRigDetail\(rig\)[\s\S]*?startCurrentRigPoll\(\)/,
    );
    assert.ok(
      showRigBlock,
      'showRigDetail should call startCurrentRigPoll',
    );
  });

  it('stops current rig poll when navigating back to list', () => {
    const backBlock = spiderJs.match(
      /function backToList\(\)[\s\S]*?stopCurrentRigPoll\(\)/,
    );
    assert.ok(
      backBlock,
      'backToList should call stopCurrentRigPoll',
    );
  });

  it('stops current rig poll when selecting a new rig', () => {
    const showRigBlock = spiderJs.match(
      /function showRigDetail\(rig\)[\s\S]*?stopCurrentRigPoll\(\)/,
    );
    assert.ok(
      showRigBlock,
      'showRigDetail should call stopCurrentRigPoll before starting new poll',
    );
  });

  it('fetchCurrentRigQuiet fetches /api/rig/show with rig id', () => {
    assert.match(
      spiderJs,
      /function fetchCurrentRigQuiet\(\)/,
      'should define fetchCurrentRigQuiet',
    );
    assert.match(
      spiderJs,
      /\/api\/rig\/show\?id=/,
      'fetchCurrentRigQuiet should fetch /api/rig/show',
    );
  });

  it('fetchCurrentRigQuiet preserves selectedEngineId across polls', () => {
    // The poll handler should find the updated engine by selectedEngineId.
    // Use a greedy match to capture the whole function body up to the next
    // top-level function declaration.
    const pollBlock = spiderJs.match(
      /function fetchCurrentRigQuiet[\s\S]*?(?=\n  function )/,
    );
    assert.ok(pollBlock, 'should find fetchCurrentRigQuiet');
    assert.match(
      pollBlock[0],
      /selectedEngineId/,
      'should reference selectedEngineId to preserve selection',
    );
  });

  it('fetchCurrentRigQuiet stops polling on terminal status', () => {
    const pollBlock = spiderJs.match(
      /function fetchCurrentRigQuiet[\s\S]*?(?=\n  function )/,
    );
    assert.ok(pollBlock, 'should find fetchCurrentRigQuiet');
    assert.match(
      pollBlock[0],
      /isRigInFlight/,
      'should check isRigInFlight and stop when terminal',
    );
  });

  it('refresh button resets rig list poll cycle', () => {
    const refreshBlock = spiderJs.match(
      /refresh-btn[\s\S]*?fetchRigs/,
    );
    assert.ok(refreshBlock, 'should find refresh button handler');
    assert.match(
      refreshBlock[0],
      /stopRigListPoll\(\)/,
      'refresh button should stop existing poll before fetching',
    );
  });

  it('rig list quiet poll stops itself when no in-flight rigs remain', () => {
    const quietBlock = spiderJs.match(
      /function fetchRigListQuiet[\s\S]*?stopRigListPoll/,
    );
    assert.ok(quietBlock, 'should find fetchRigListQuiet');
    assert.match(
      quietBlock[0],
      /hasInFlight/,
      'should check for in-flight rigs and stop poll if none',
    );
  });
});

// ── Engine-detail in-place update (no flicker / no scroll reset) ────────

describe('spider.js engine-detail stable-skeleton + updater', () => {
  it('defines updateEngineDetail as a separate function from showEngineDetail', () => {
    assert.match(
      spiderJs,
      /function updateEngineDetail\(engine\)/,
      'should define updateEngineDetail for the poll path',
    );
    assert.match(
      spiderJs,
      /function showEngineDetail\(engine\)/,
      'should still define showEngineDetail for the click path',
    );
  });

  it('defines a buildEngineDetailSkeleton that establishes stable field ids', () => {
    assert.match(
      spiderJs,
      /function buildEngineDetailSkeleton\(/,
      'should define a one-time skeleton builder',
    );
  });

  it('skeleton declares stable id containers for the value-bearing fields', () => {
    // Spot-check a representative subset of the stable-id contract.
    const expectedIds = [
      'ed-status',
      'ed-design-id',
      'ed-upstream',
      'ed-started-at',
      'ed-completed-at',
      'ed-elapsed',
      'ed-error',
      'ed-session-id',
      'ed-block-type',
      'ed-cost-input',
      'ed-cost-output',
      'ed-cost-usd',
      'ed-givens-code',
      'ed-yields-code',
      'ed-cancel-container',
    ];
    for (const id of expectedIds) {
      assert.match(
        spiderJs,
        new RegExp(`id="${id}"`),
        `skeleton should define a stable id container for ${id}`,
      );
    }
  });

  it('the old #cost-placeholder insertAdjacentHTML trick is gone', () => {
    assert.doesNotMatch(
      spiderJs,
      /id="cost-placeholder"/,
      'skeleton should not use the old #cost-placeholder span',
    );
    assert.doesNotMatch(
      spiderJs,
      /insertAdjacentHTML\('beforebegin'/,
      'cost rendering should not use insertAdjacentHTML anymore',
    );
  });

  it('the rig poll path calls updateEngineDetail (not showEngineDetail) for the selected engine', () => {
    const pollBlock = spiderJs.match(
      /function fetchCurrentRigQuiet[\s\S]*?(?=\n  function )/,
    );
    assert.ok(pollBlock, 'should find fetchCurrentRigQuiet');
    assert.match(
      pollBlock[0],
      /updateEngineDetail\(/,
      'fetchCurrentRigQuiet should call updateEngineDetail on poll',
    );
    assert.doesNotMatch(
      pollBlock[0],
      /showEngineDetail\(/,
      'fetchCurrentRigQuiet must NOT call showEngineDetail (that would re-open SSE and rebuild the panel)',
    );
  });

  it('updateEngineDetail does not rewrite the engine-detail-body innerHTML', () => {
    const updaterBlock = spiderJs.match(
      /function updateEngineDetail\(engine\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(updaterBlock, 'should find updateEngineDetail body');
    assert.doesNotMatch(
      updaterBlock[0],
      /engine-detail-body[\s\S]*?innerHTML\s*=/,
      'updateEngineDetail must not rewrite #engine-detail-body innerHTML',
    );
  });
});

// ── SSE removal regression guard ────────────────────────────────────────

describe('spider.js SSE removal', () => {
  // The SSE path was removed because animator.subscribeToSession does not
  // work across processes (detached sessions return null). The UI now
  // polls /api/spider/session-transcript uniformly for all sessions.
  // These guards keep the SSE code from creeping back in.

  it('has no EventSource constructor in the UI code', () => {
    assert.doesNotMatch(
      spiderJs,
      /new\s+EventSource/,
      'UI should not construct EventSource (SSE was removed)',
    );
  });

  it('does not define streamSessionId or streamDone state', () => {
    assert.doesNotMatch(spiderJs, /\bstreamSessionId\b/, 'streamSessionId should not exist');
    assert.doesNotMatch(spiderJs, /\bstreamDone\b/, 'streamDone should not exist');
  });

  it('does not define ensureSessionStream / openSessionStream / stopSessionStream', () => {
    assert.doesNotMatch(spiderJs, /function\s+ensureSessionStream/, 'ensureSessionStream removed');
    assert.doesNotMatch(spiderJs, /function\s+openSessionStream/, 'openSessionStream removed');
    assert.doesNotMatch(spiderJs, /function\s+stopSessionStream/, 'stopSessionStream removed');
  });

  it('does not reference /api/spider/session-stream', () => {
    assert.doesNotMatch(
      spiderJs,
      /\/api\/spider\/session-stream/,
      'UI should not reference the SSE endpoint',
    );
  });
});

// ── Session transcript polling ──────────────────────────────────────────

describe('spider.js session transcript polling', () => {
  it('declares transcriptPollSessionId in module scope', () => {
    assert.match(
      spiderJs,
      /var transcriptPollSessionId\s*=\s*null/,
      'should track transcriptPollSessionId in module scope',
    );
  });

  it('declares TRANSCRIPT_POLL_INTERVAL at 2000 ms', () => {
    assert.match(
      spiderJs,
      /var TRANSCRIPT_POLL_INTERVAL\s*=\s*2000/,
      'should set the polling interval to 2000 ms',
    );
  });

  it('defines startSessionTranscriptPoll that dedupes on sessionId', () => {
    assert.match(
      spiderJs,
      /function startSessionTranscriptPoll\(/,
      'should define startSessionTranscriptPoll',
    );
    const startBlock = spiderJs.match(
      /function startSessionTranscriptPoll[\s\S]*?(?=\n  function )/,
    );
    assert.ok(startBlock, 'should find startSessionTranscriptPoll body');
    assert.match(
      startBlock[0],
      /sessionId\s*===\s*transcriptPollSessionId/,
      'startSessionTranscriptPoll should early-return when id is unchanged',
    );
  });

  it('defines stopSessionTranscriptPoll that clears transcriptPollSessionId', () => {
    assert.match(
      spiderJs,
      /function stopSessionTranscriptPoll\(/,
      'should define stopSessionTranscriptPoll',
    );
    const stopBlock = spiderJs.match(
      /function stopSessionTranscriptPoll[\s\S]*?(?=\n  function )/,
    );
    assert.ok(stopBlock, 'should find stopSessionTranscriptPoll body');
    assert.match(
      stopBlock[0],
      /transcriptPollSessionId\s*=\s*null/,
      'stopSessionTranscriptPoll should null out transcriptPollSessionId',
    );
    assert.match(
      stopBlock[0],
      /stopSessionPoll\(/,
      'stopSessionTranscriptPoll should clear the underlying timer',
    );
  });

  it('defines fetchAndRenderTranscript that calls /api/spider/session-transcript', () => {
    assert.match(
      spiderJs,
      /function fetchAndRenderTranscript\(/,
      'should define fetchAndRenderTranscript',
    );
    const fetchBlock = spiderJs.match(
      /function fetchAndRenderTranscript[\s\S]*?(?=\n  function )/,
    );
    assert.ok(fetchBlock, 'should find fetchAndRenderTranscript body');
    assert.match(
      fetchBlock[0],
      /\/api\/spider\/session-transcript\?sessionId=/,
      'fetchAndRenderTranscript should hit the transcript endpoint',
    );
  });

  it('fetchAndRenderTranscript stops polling on terminal session status', () => {
    const fetchBlock = spiderJs.match(
      /function fetchAndRenderTranscript[\s\S]*?(?=\n  function )/,
    );
    assert.ok(fetchBlock, 'should find fetchAndRenderTranscript body');
    assert.match(
      fetchBlock[0],
      /stopSessionTranscriptPoll\(/,
      'should tear down polling when the session reaches a terminal status',
    );
  });

  it('fetchAndRenderTranscript captures atBottom before replacing textarea value', () => {
    const fetchBlock = spiderJs.match(
      /function fetchAndRenderTranscript[\s\S]*?(?=\n  function )/,
    );
    assert.ok(fetchBlock, 'should find fetchAndRenderTranscript body');
    assert.match(
      fetchBlock[0],
      /var atBottom\s*=/,
      'should capture atBottom before mutating the textarea',
    );
    assert.match(
      fetchBlock[0],
      /if\s*\(atBottom\)/,
      'should restore scroll only when atBottom was true',
    );
  });

  it('updateEngineDetail drives transcript polling via startSessionTranscriptPoll', () => {
    const updaterBlock = spiderJs.match(
      /function updateEngineDetail\(engine\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(updaterBlock, 'should find updateEngineDetail');
    assert.match(
      updaterBlock[0],
      /startSessionTranscriptPoll\(/,
      'updateEngineDetail should call startSessionTranscriptPoll every rig poll (dedup handles no-ops)',
    );
  });

  it('navigating away stops transcript polling', () => {
    const backBlock = spiderJs.match(
      /function backToList\(\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(backBlock, 'should find backToList');
    assert.match(
      backBlock[0],
      /stopSessionTranscriptPoll\(/,
      'backToList should stop transcript polling',
    );
    const showRigBlock = spiderJs.match(
      /function showRigDetail\(rig\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(showRigBlock, 'should find showRigDetail');
    assert.match(
      showRigBlock[0],
      /stopSessionTranscriptPoll\(/,
      'showRigDetail should stop any prior transcript poll before switching rigs',
    );
  });
});

// ── Elapsed ticker ──────────────────────────────────────────────────────

describe('spider.js elapsed ticker', () => {
  it('declares elapsedTimer and elapsedTimerStartedAt in module scope', () => {
    assert.match(
      spiderJs,
      /var elapsedTimer\s*=\s*null/,
      'should declare elapsedTimer state',
    );
    assert.match(
      spiderJs,
      /var elapsedTimerStartedAt\s*=\s*null/,
      'should declare elapsedTimerStartedAt state',
    );
  });

  it('declares ELAPSED_TICK_INTERVAL at 1000 ms', () => {
    assert.match(
      spiderJs,
      /var ELAPSED_TICK_INTERVAL\s*=\s*1000/,
      'elapsed ticker should tick every 1000 ms',
    );
  });

  it('defines startElapsedTimer that dedupes on startedAt', () => {
    assert.match(
      spiderJs,
      /function startElapsedTimer\(/,
      'should define startElapsedTimer',
    );
    const startBlock = spiderJs.match(
      /function startElapsedTimer[\s\S]*?(?=\n  function )/,
    );
    assert.ok(startBlock, 'should find startElapsedTimer body');
    assert.match(
      startBlock[0],
      /elapsedTimerStartedAt\s*===\s*startedAt/,
      'startElapsedTimer should early-return when startedAt is unchanged',
    );
    assert.match(
      startBlock[0],
      /formatElapsed\(startedAt,\s*new Date\(\)\.toISOString\(\)\)/,
      'startElapsedTimer tick should call formatElapsed with now()',
    );
  });

  it('defines stopElapsedTimer that clears the interval', () => {
    assert.match(
      spiderJs,
      /function stopElapsedTimer\(/,
      'should define stopElapsedTimer',
    );
    const stopBlock = spiderJs.match(
      /function stopElapsedTimer[\s\S]*?(?=\n  function )/,
    );
    assert.ok(stopBlock, 'should find stopElapsedTimer body');
    assert.match(
      stopBlock[0],
      /clearInterval\(elapsedTimer\)/,
      'stopElapsedTimer should clear the interval',
    );
  });

  it('updateEngineDetail starts the ticker for running engines with a startedAt', () => {
    const updaterBlock = spiderJs.match(
      /function updateEngineDetail\(engine\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(updaterBlock, 'should find updateEngineDetail');
    assert.match(
      updaterBlock[0],
      /engine\.status\s*===\s*'running'\s*&&\s*engine\.startedAt[\s\S]*?startElapsedTimer\(/,
      'updateEngineDetail should start the elapsed ticker for running engines',
    );
  });

  it('updateEngineDetail stops the ticker when engine completes', () => {
    const updaterBlock = spiderJs.match(
      /function updateEngineDetail\(engine\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(updaterBlock, 'should find updateEngineDetail');
    assert.match(
      updaterBlock[0],
      /engine\.status\s*===\s*'completed'[\s\S]*?stopElapsedTimer\(/,
      'updateEngineDetail should stop the elapsed ticker on completion',
    );
  });

  it('static "running…" placeholder is replaced by the live ticker', () => {
    // The old implementation wrote a literal "running…" span. Now the
    // ticker writes a live elapsed value every second. Regression guard
    // against re-introducing the static placeholder.
    assert.doesNotMatch(
      spiderJs,
      /<span class="elapsed-running">running\\u2026<\/span>/,
      'static "running…" placeholder should be gone',
    );
  });

  it('navigating away stops the elapsed ticker', () => {
    const backBlock = spiderJs.match(
      /function backToList\(\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(backBlock, 'should find backToList');
    assert.match(
      backBlock[0],
      /stopElapsedTimer\(/,
      'backToList should stop the elapsed ticker',
    );
    const showRigBlock = spiderJs.match(
      /function showRigDetail\(rig\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(showRigBlock, 'should find showRigDetail');
    assert.match(
      showRigBlock[0],
      /stopElapsedTimer\(/,
      'showRigDetail should stop any prior ticker before switching rigs',
    );
  });
});

// ── Pipeline renderer keyed in-place update ─────────────────────────────

describe('spider.js pipeline keyed update', () => {
  it('renderPipelineInto indexes existing nodes by data-engine-id', () => {
    const block = spiderJs.match(
      /function renderPipelineInto\([\s\S]*?(?=\n  function )/,
    );
    assert.ok(block, 'should find renderPipelineInto');
    assert.match(
      block[0],
      /querySelectorAll\(['"]\.pipeline-node['"]\)/,
      'renderPipelineInto should look up existing pipeline-node children',
    );
    assert.match(
      block[0],
      /getAttribute\(['"]data-engine-id['"]\)/,
      'renderPipelineInto should key existing nodes by data-engine-id',
    );
  });

  it('renderPipelineInto has a fast path that patches in place when order is unchanged', () => {
    const block = spiderJs.match(
      /function renderPipelineInto\([\s\S]*?(?=\n  function )/,
    );
    assert.ok(block, 'should find renderPipelineInto');
    assert.match(
      block[0],
      /orderUnchanged/,
      'should compute an orderUnchanged flag for the keyed fast path',
    );
  });

  it('exposes updatePipelineNode for in-place badge/selection updates', () => {
    assert.match(
      spiderJs,
      /function updatePipelineNode\(node, engine\)/,
      'should define updatePipelineNode helper for in-place node updates',
    );
  });

  it('pipeline node carries a class hook for the status badge', () => {
    // Without a class hook, the keyed-update path can't unambiguously
    // target the status badge inside a node.
    assert.match(
      spiderJs,
      /pipeline-node-status/,
      'pipeline-node-status class hook should mark the badge for updates',
    );
  });
});

// ── Cost fetch gated on transition to completed ─────────────────────────

describe('spider.js session cost fetch gating', () => {
  it('declares costFetchedFor cache in module scope', () => {
    assert.match(
      spiderJs,
      /var costFetchedFor\s*=\s*\{\}/,
      'should declare costFetchedFor cache to gate the cost fetch',
    );
  });

  it('cost fetch is not fired unconditionally on every render', () => {
    // Locate the call to /api/session/show — it must be inside a guarded
    // helper, not directly inside updateEngineDetail's per-render path.
    const updaterBlock = spiderJs.match(
      /function updateEngineDetail\(engine\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(updaterBlock, 'should find updateEngineDetail');
    assert.doesNotMatch(
      updaterBlock[0],
      /fetch\(['"]\/api\/session\/show/,
      'updateEngineDetail should not call /api/session/show directly',
    );
    assert.match(
      updaterBlock[0],
      /costFetchedFor\[engine\.id\]/,
      'updateEngineDetail should consult costFetchedFor before requesting cost',
    );
  });

  it('cost fetch helper exists and targets /api/session/show', () => {
    assert.match(
      spiderJs,
      /function fetchSessionCost\(/,
      'should define a dedicated fetchSessionCost helper',
    );
    const helperBlock = spiderJs.match(
      /function fetchSessionCost\([\s\S]*?(?=\n  function )/,
    );
    assert.ok(helperBlock, 'should find fetchSessionCost body');
    assert.match(
      helperBlock[0],
      /\/api\/session\/show\?id=/,
      'fetchSessionCost should call the session show endpoint',
    );
  });

  it('updateEngineDetail tracks engine status across polls to detect transition', () => {
    const updaterBlock = spiderJs.match(
      /function updateEngineDetail\(engine\)[\s\S]*?(?=\n  function )/,
    );
    assert.ok(updaterBlock, 'should find updateEngineDetail');
    assert.match(
      updaterBlock[0],
      /engineStatusByEngineId/,
      'updateEngineDetail should record engine status to detect transitions',
    );
  });
});
