/**
 * Spider UI — static asset regression tests.
 *
 * These tests verify the HTML structure generated by spider.js for the rig
 * list table.  Because spider.js is a vanilla-JS IIFE (no modules), we
 * validate the source text directly to ensure structural invariants hold.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const spiderJs = readFileSync(resolve(__dirname, 'spider.js'), 'utf-8');
const spiderCss = readFileSync(resolve(__dirname, 'spider.css'), 'utf-8');
const indexHtml = readFileSync(resolve(__dirname, 'index.html'), 'utf-8');

// ── Rig list row structure ──────────────────────────────────────────────

describe('spider.js rig list row HTML', () => {
  it('renders the writ-title cell as a rig-link anchor', () => {
    // The row template should contain a <td> with a rig-link anchor for the
    // writ title (the second <td> in each row).  We match the template
    // fragment that builds the writ-title cell.
    const writTitleCellPattern =
      /<td><a class="rig-link" href="#" data-rig-id="[^"]*"\s*>\s*'\s*\+\s*esc\(writTitle\)/;
    assert.match(
      spiderJs,
      writTitleCellPattern,
      'writ-title cell should be a clickable rig-link anchor',
    );
  });

  it('renders the rig-id cell as a rig-link anchor', () => {
    const rigIdCellPattern =
      /<td><a class="rig-link" href="#" data-rig-id="[^"]*"\s*>\s*'\s*\+\s*esc\(rig\.id\)/;
    assert.match(
      spiderJs,
      rigIdCellPattern,
      'rig-id cell should be a clickable rig-link anchor',
    );
  });

  it('writ-title and rig-id cells share the same rig-link class', () => {
    // Both cells must use the same class so the click handler wires them
    // identically.  Count rig-link anchors in the row template.
    const rowTemplateMatch = spiderJs.match(
      /var rows = filtered\.map\(function \(rig\) \{[\s\S]*?\.join\(''\)/,
    );
    assert.ok(rowTemplateMatch, 'should find the row template block');
    const rowTemplate = rowTemplateMatch[0];

    const rigLinkCount = (rowTemplate.match(/class="rig-link"/g) || []).length;
    assert.ok(
      rigLinkCount >= 2,
      `expected at least 2 rig-link anchors in the row template, found ${rigLinkCount}`,
    );
  });

  it('writ-title cell is NOT rendered as plain text', () => {
    // Regression guard: the old pattern was just  '<td>' + esc(writTitle) + '</td>'
    // with no anchor.  Ensure that pattern no longer exists.
    const plainTitlePattern = /'<td>'\s*\+\s*esc\(writTitle\)\s*\+\s*'<\/td>'/;
    assert.doesNotMatch(
      spiderJs,
      plainTitlePattern,
      'writ-title cell must not be rendered as plain (non-linked) text',
    );
  });
});

// ── Cancellation UI ──────────────────────────────────────────────────────

describe('spider.js cancel button', () => {
  it('renders a cancel button with id "cancel-engine-btn"', () => {
    assert.match(
      spiderJs,
      /id="cancel-engine-btn"/,
      'should contain a cancel button element',
    );
  });

  it('cancel button has btn--danger class', () => {
    assert.match(
      spiderJs,
      /class="btn btn--danger" id="cancel-engine-btn"/,
      'cancel button should have btn--danger class',
    );
  });

  it('cancel button sends POST to /api/rig/cancel', () => {
    assert.match(
      spiderJs,
      /method:\s*'POST'/,
      'should use POST method for cancel request',
    );
    assert.match(
      spiderJs,
      /\/api\/rig\/cancel/,
      'should call the cancel API endpoint',
    );
  });

  it('cancel button is conditional on rig status running or blocked', () => {
    assert.match(
      spiderJs,
      /currentRig\.status === 'running' \|\| currentRig\.status === 'blocked'/,
      'showCancel should check for running or blocked rig status',
    );
  });

  it('cancel button is hidden for terminal rig statuses', () => {
    assert.match(
      spiderJs,
      /currentRig\.status === 'cancelled'/,
      'should check for cancelled status to hide button',
    );
  });

  it('cancel button does NOT use DELETE method', () => {
    // DELETE with JSON body is unreliable across HTTP stacks.
    // The cancel fetch must use POST to match the auto-generated tool route.
    const cancelFetchBlock = spiderJs.match(
      /fetch\('\/api\/rig\/cancel'[\s\S]*?\)/,
    );
    assert.ok(cancelFetchBlock, 'should find the cancel fetch call');
    assert.doesNotMatch(
      cancelFetchBlock[0],
      /method:\s*'DELETE'/,
      'cancel fetch must not use DELETE method',
    );
  });

  it('cancel handler uses the cancel API response directly (no redundant rig-show fetch)', () => {
    // After the cancel fetch, the handler should call r.json() on the cancel
    // response itself, not make a second fetch to /api/rig/show.
    const cancelBlock = spiderJs.match(
      /fetch\('\/api\/rig\/cancel'[\s\S]*?\.catch/,
    );
    assert.ok(cancelBlock, 'should find the cancel fetch chain');
    assert.doesNotMatch(
      cancelBlock[0],
      /fetch\('\/api\/rig\/show/,
      'cancel handler should not make a redundant rig-show fetch',
    );
  });

  it('cancel handler calls preventDefault on click event', () => {
    // The cancel click handler should call e.preventDefault() to guard
    // against any default button behaviour.
    const cancelHandler = spiderJs.match(
      /addEventListener\('click', function \(e\)[\s\S]*?e\.preventDefault\(\)/,
    );
    assert.ok(
      cancelHandler,
      'cancel click handler should accept the event and call preventDefault',
    );
  });
});

describe('spider.js badgeClass for cancelled', () => {
  it('badgeClass returns "badge--cancelled" for cancelled status', () => {
    assert.match(
      spiderJs,
      /case 'cancelled':\s*return 'badge--cancelled'/,
      'badgeClass should return badge--cancelled for cancelled status',
    );
  });

  it('cancelled is not grouped with pending in badgeClass', () => {
    // Ensure cancelled has its own case, not falling through with pending
    assert.doesNotMatch(
      spiderJs,
      /case 'pending':\s*case 'cancelled'/,
      'cancelled should not fall through with pending',
    );
  });
});

describe('spider.css cancelled badge styling', () => {
  it('contains .badge--cancelled rule', () => {
    assert.match(
      spiderCss,
      /\.badge--cancelled/,
      'spider.css should contain .badge--cancelled rule',
    );
  });

  it('.badge--cancelled has text-decoration: line-through', () => {
    assert.match(
      spiderCss,
      /\.badge--cancelled[\s\S]*?text-decoration:\s*line-through/,
      'badge--cancelled should have line-through text decoration',
    );
  });

  it('.badge--cancelled has opacity', () => {
    assert.match(
      spiderCss,
      /\.badge--cancelled[\s\S]*?opacity:\s*0\.6/,
      'badge--cancelled should have reduced opacity',
    );
  });
});

describe('index.html status filter includes cancelled', () => {
  it('status filter has cancelled option', () => {
    assert.match(
      indexHtml,
      /<option value="cancelled">cancelled<\/option>/,
      'status filter should include cancelled option',
    );
  });

  it('cancelled option appears after blocked', () => {
    const blockedIdx = indexHtml.indexOf('<option value="blocked">');
    const cancelledIdx = indexHtml.indexOf('<option value="cancelled">');
    assert.ok(cancelledIdx > blockedIdx, 'cancelled option should appear after blocked');
  });
});

// ── Rig auto-polling ────────────────────────────────────────────────────

describe('spider.js rig list polling', () => {
  it('declares rigListPollTimer state variable', () => {
    assert.match(
      spiderJs,
      /var rigListPollTimer\s*=\s*null/,
      'should declare rigListPollTimer state variable',
    );
  });

  it('declares currentRigPollTimer state variable', () => {
    assert.match(
      spiderJs,
      /var currentRigPollTimer\s*=\s*null/,
      'should declare currentRigPollTimer state variable',
    );
  });

  it('declares RIG_POLL_INTERVAL constant', () => {
    assert.match(
      spiderJs,
      /var RIG_POLL_INTERVAL\s*=\s*2000/,
      'should declare RIG_POLL_INTERVAL at 2000ms',
    );
  });

  it('defines isRigInFlight helper checking running and blocked', () => {
    assert.match(
      spiderJs,
      /function isRigInFlight\(rig\)/,
      'should define isRigInFlight helper',
    );
    assert.match(
      spiderJs,
      /rig\.status === 'running' \|\| rig\.status === 'blocked'/,
      'isRigInFlight should check running or blocked',
    );
  });

  it('defines stopRigListPoll that clears the interval', () => {
    assert.match(
      spiderJs,
      /function stopRigListPoll\(\)/,
      'should define stopRigListPoll',
    );
    assert.match(
      spiderJs,
      /clearInterval\(rigListPollTimer\)/,
      'stopRigListPoll should clear rigListPollTimer',
    );
  });

  it('defines stopCurrentRigPoll that clears the interval', () => {
    assert.match(
      spiderJs,
      /function stopCurrentRigPoll\(\)/,
      'should define stopCurrentRigPoll',
    );
    assert.match(
      spiderJs,
      /clearInterval\(currentRigPollTimer\)/,
      'stopCurrentRigPoll should clear currentRigPollTimer',
    );
  });

  it('starts rig list polling after fetchRigs succeeds', () => {
    // The fetchRigs promise chain should call startRigListPollIfNeeded
    const fetchRigsBlock = spiderJs.match(
      /function fetchRigs\([\s\S]*?\.catch/,
    );
    assert.ok(fetchRigsBlock, 'should find fetchRigs function');
    assert.match(
      fetchRigsBlock[0],
      /startRigListPollIfNeeded\(\)/,
      'fetchRigs should call startRigListPollIfNeeded after rendering',
    );
  });

  it('starts current rig polling in showRigDetail', () => {
    const showRigBlock = spiderJs.match(
      /function showRigDetail\(rig\)[\s\S]*?startCurrentRigPoll\(\)/,
    );
    assert.ok(
      showRigBlock,
      'showRigDetail should call startCurrentRigPoll',
    );
  });

  it('stops current rig poll when navigating back to list', () => {
    const backBlock = spiderJs.match(
      /function backToList\(\)[\s\S]*?stopCurrentRigPoll\(\)/,
    );
    assert.ok(
      backBlock,
      'backToList should call stopCurrentRigPoll',
    );
  });

  it('stops current rig poll when selecting a new rig', () => {
    const showRigBlock = spiderJs.match(
      /function showRigDetail\(rig\)[\s\S]*?stopCurrentRigPoll\(\)/,
    );
    assert.ok(
      showRigBlock,
      'showRigDetail should call stopCurrentRigPoll before starting new poll',
    );
  });

  it('fetchCurrentRigQuiet fetches /api/rig/show with rig id', () => {
    assert.match(
      spiderJs,
      /function fetchCurrentRigQuiet\(\)/,
      'should define fetchCurrentRigQuiet',
    );
    assert.match(
      spiderJs,
      /\/api\/rig\/show\?id=/,
      'fetchCurrentRigQuiet should fetch /api/rig/show',
    );
  });

  it('fetchCurrentRigQuiet preserves selectedEngineId across polls', () => {
    // The poll handler should find the updated engine by selectedEngineId.
    // Use a greedy match to capture the whole function body up to the next
    // top-level function declaration.
    const pollBlock = spiderJs.match(
      /function fetchCurrentRigQuiet[\s\S]*?(?=\n  function )/,
    );
    assert.ok(pollBlock, 'should find fetchCurrentRigQuiet');
    assert.match(
      pollBlock[0],
      /selectedEngineId/,
      'should reference selectedEngineId to preserve selection',
    );
  });

  it('fetchCurrentRigQuiet stops polling on terminal status', () => {
    const pollBlock = spiderJs.match(
      /function fetchCurrentRigQuiet[\s\S]*?(?=\n  function )/,
    );
    assert.ok(pollBlock, 'should find fetchCurrentRigQuiet');
    assert.match(
      pollBlock[0],
      /isRigInFlight/,
      'should check isRigInFlight and stop when terminal',
    );
  });

  it('refresh button resets rig list poll cycle', () => {
    const refreshBlock = spiderJs.match(
      /refresh-btn[\s\S]*?fetchRigs/,
    );
    assert.ok(refreshBlock, 'should find refresh button handler');
    assert.match(
      refreshBlock[0],
      /stopRigListPoll\(\)/,
      'refresh button should stop existing poll before fetching',
    );
  });

  it('rig list quiet poll stops itself when no in-flight rigs remain', () => {
    const quietBlock = spiderJs.match(
      /function fetchRigListQuiet[\s\S]*?stopRigListPoll/,
    );
    assert.ok(quietBlock, 'should find fetchRigListQuiet');
    assert.match(
      quietBlock[0],
      /hasInFlight/,
      'should check for in-flight rigs and stop poll if none',
    );
  });
});
